# 
# Copyright 2015 Stefano Terna
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

version: '2'

services:

  iottlycore:
    #overlays application files with host dev ones:
    environment:
      - PUBLIC_HOST=${HOST_IP_ADDRESS}
      - PUBLIC_XMPP_HOST=${HOST_IP_ADDRESS}
      - PUBLIC_HOST_PORT_PATTERN={}:8550
    volumes:
     - ../iottly-core/iottly_core:/iottly-core/iottly_core
    # ports:
    #  - "8520:8520" 


  iottlyagentinstallers:
    volumes: 
     - ../iottly-device-agent-py/iottly-device-agent-py-installers:/iottly-device-agent-py-installers

  iottlyconsole:
    #overlays application files with host dev ones:
    volumes: 
     - ../iottly-console/iottly_console:/iottly_console

  iottlyfwsnippettpl:
    volumes: 
     - ../iottly-core/fw-snippet-tpl:/fw-snippet-tpl

  iottlyclientui:
    #overlays application files with host dev ones:
    volumes: 
     - ../iottly-client-UI/iottly_client_UI:/iottly_client_UI

  iottlyhttploadbalancer:
    ports:
      - "8550:8550" # api        
      - "8560:8560" # web socket 
      - "8580:8580" # front-end    
    volumes: 
     - ../iottly-http-load-balancer/nginx_conf_dev/conf.d:/etc/nginx/conf.d