git clone https://github.com/iottly/iottly-db.git
git clone https://github.com/iottly/iottly-xmpp-broker.git
git clone https://github.com/iottly/iottly-mqtt-broker.git
git clone https://github.com/iottly/iottly-licence-adder.git
git clone https://github.com/iottly/iottly-httpforward.git
git clone https://github.com/iottly/iottly-docker.git
git clone https://github.com/iottly/iottly-device-agent-py.git
git clone https://github.com/iottly/iottly-console.git
git clone https://github.com/iottly/iottly-client-UI.git
git clone https://github.com/iottly/iottly-client-core.git
git clone https://github.com/iottly/iottly-core.git
git clone https://github.com/iottly/iottly-http-load-balancer.git
